---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litellm-proxy
  namespace: mlops
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - litellm.adeoaiengine.ecouncil.ae
      secretName: litellm.adeoaiengine.ecouncil.ae-tls
  rules:
    - host: litellm.adeoaiengine.ecouncil.ae
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: litellm-proxy
                port:
                  number: 4000
