---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: litellm-proxy-service-monitor
  namespace: mlops
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 30s
      path: /metrics/
      port: http
  namespaceSelector:
    matchNames:
      - mlops
  selector:
    matchLabels:
      app: litellm-proxy
