model_list:
  - model_name: omnivoice
    litellm_params:
      model: omnivoice/omnivoice
      api_base: http://localhost:18080

litellm_settings:
  store_model_in_db: false
  drop_params: true
  cache: false

router_settings:
  routing_strategy: usage-based-routing-v2
  optional_pre_call_checks:
    - enforce_model_rate_limits

general_settings:
  master_key: sk-1234
